import React from 'react';
import { FiCpu, FiMessageCircle } from 'react-icons/fi';
import { Link } from 'react-router-dom';

const AiFeatures = () => {
  const features = [
    {
      icon: <FiMessageCircle className="w-12 h-12 text-blue-500 mb-4" />,
      title: 'AI Doubt Solver',
      description: 'Stuck on a concept? Get instant, step-by-step solutions from our AI assistant, available 24/7.',
      link: '/ai-doubt-solver',
      linkText: 'Ask Now',
    },
    {
      icon: <FiCpu className="w-12 h-12 text-blue-500 mb-4" />,
      title: 'AI Quiz Taker',
      description: 'Test your knowledge with personalized quizzes generated by our AI. Track your progress and master your subjects.',
      link: '/ai-quiz-taker',
      linkText: 'Start Quiz',
    },
  ];

  return (
    <div className="pt-17 bg-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-extrabold text-gray-900 sm:text-4xl">
            Supercharge Your Learning with AI
          </h2>
          <p className="mt-4 text-lg text-gray-600">
            Our intelligent tools are here to help you succeed.
          </p>
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 max-w-4xl mx-auto">
          {features.map((feature, index) => (
            <div
              key={index}
              className="bg-white rounded-xl shadow-lg p-8 flex flex-col items-center text-center transform hover:scale-105 transition-transform duration-300"
            >
              {feature.icon}
              <h3 className="text-2xl font-bold text-gray-800 mb-2">{feature.title}</h3>
              <p className="text-gray-600 mb-6">{feature.description}</p>
              <Link
                to={feature.link}
                className="mt-auto inline-block bg-blue-600 text-white font-semibold px-5 py-2.5 rounded-lg hover:bg-blue-700 transition-all duration-300 shadow-md hover:shadow-lg"
              >
                {feature.linkText}
              </Link>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};

export default AiFeatures; 